name: example_server
description: An example events-service server
version: 1.0.0

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
