name: pulse_events_sdk
description: A Flutter SDK for tracking and managing events in mobile applications
version: 1.0.0
homepage: https://github.com/Uni-Cards/Pulse
repository: https://github.com/Uni-Cards/Pulse
issue_tracker: https://github.com/Uni-Cards/Pulse/issues

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  get_it: ^8.0.3
  path: ^1.9.0
  path_provider: ^2.1.3
  uuid: ^4.5.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
